### ISSUE TITLE
PowerNBT fails to start on Cauldron java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by deepvelocity** [DPOH-VAR/PowerNBT#8]
Error on startup: http://pastie.org/9710609
Server version: Cauldron-MCPC-Plus version git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
PowerNBT version: 0.7.3.1

This PowerNBT version runs perfectly on the latest spigot.

**Comment by DPOH-VAR** [comment]
PowerNBT 0.8.2 work with cauldron-1.7.10-1.1207.01.198-server
